# PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-notes-db-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/flask-notes-db
    type: DirectoryOrCreate

---
# PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-notes-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-notes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-notes-app
  template:
    metadata:
      labels:
        app: flask-notes-app
    spec:
      containers:
        - name: flask-notes-app
          image: kenway213beep301/flask-notes-app@sha256:13a3ee303cd703ed574d0538df9465004e91c0583e70d42d2c391d21c9e1d92d
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-notes-secret
                  key: SECRET_KEY
          volumeMounts:
            - name: flask-notes-db
              mountPath: /app/database
      volumes:
        - name: flask-notes-db
          persistentVolumeClaim:
            claimName: flask-notes-db-pvc

---
# LoadBalancer service
apiVersion: v1
kind: Service
metadata:
  name: flask-notes-service
spec:
  selector:
    app: flask-notes-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

